from __future__ import annotations

from typing import Any, Protocol
from .memory import MemoryItem


class MemoryPort(Protocol):
    async def search(self, query: str, top_k: int = 8, context_budget: int = 4000, **kwargs: Any) -> list[MemoryItem]: ...
    async def store(self, text: str, metadata: dict[str, Any] | None = None) -> bool: ...
    async def update(self, memory_id: str, text: str, metadata: dict[str, Any] | None = None) -> bool: ...
    async def delete(self, memory_id: str) -> bool: ...
    async def health(self) -> bool: ...
