const $ = (id) => document.getElementById(id);
const loginView = $('loginView'); const appView = $('appView');
const input = $('messageInput'); const messages = $('messages'); let toastTimer;
const DEVICE_WS_URL = 'ws://36.212.7.43:8765/ws';
const DEVICE_ID = 'mg946r-001'; const DEVICE_TOKEN = 'mg946r-token';
let deviceSocket = null; let deviceReconnectTimer = null; let deviceReconnectDelay = 1000; let deviceManualClose = false;
function setText(id, value) { const node = $(id); if (node) node.textContent = value; }
function showToast(text) { const el = $('toast'); el.textContent = text; el.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove('show'), 2600); }
function setIdentity(identity) { setText('userDisplay', `${identity.username} · QQ ${identity.qq_id}`); setText('welcomeName', identity.username); loginView?.classList.add('hidden'); appView?.classList.remove('hidden'); input?.focus(); }
function addMessage(text, type) { const row = document.createElement('div'); row.className = `message-row ${type}`; const bubble = document.createElement('div'); bubble.className = 'bubble'; bubble.textContent = text; row.appendChild(bubble); messages.appendChild(row); messages.scrollTop = messages.scrollHeight; }
async function post(url, body) { const res = await fetch(url, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(body) }); const raw = await res.text(); let data; try { data = JSON.parse(raw); } catch (_) { throw new Error(res.ok ? '服务端返回了非 JSON 响应，请确认访问的是 oii 服务端口。' : `服务请求失败（${res.status}）`); } if (!res.ok) throw new Error(data.error || '请求失败'); return data; }
$('loginForm')?.addEventListener('submit', async (event) => { event.preventDefault(); const button = event.target.querySelector('button'); setText('loginError', ''); if (button) button.disabled = true; try { const data = await post('/api/sim-qq/login', { username: $('username').value.trim(), qq_id: $('qqId').value.trim() }); setIdentity(data.identity); } catch (error) { setText('loginError', error.message); } finally { if (button) button.disabled = false; } });
$('logoutButton').addEventListener('click', async () => { await post('/api/sim-qq/logout', {}); location.reload(); });
document.querySelectorAll('.guide-item').forEach((button) => button.addEventListener('click', () => { input.value = button.dataset.command; input.dispatchEvent(new Event('input')); input.focus(); }));
input?.addEventListener('input', () => { setText('charCount', `${input.value.length} / 4000`); input.style.height = 'auto'; input.style.height = `${Math.min(input.scrollHeight, 150)}px`; });
input?.addEventListener('keydown', (event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); $('messageForm')?.requestSubmit(); } });
$('messageForm').addEventListener('submit', async (event) => { event.preventDefault(); const text = input.value.trim(); if (!text) return; addMessage(text, 'outgoing'); input.value = ''; input.dispatchEvent(new Event('input')); const pending = document.createElement('div'); pending.className = 'message-row incoming'; pending.innerHTML = '<div class="bubble pending"><span></span><span></span><span></span></div>'; messages.appendChild(pending); messages.scrollTop = messages.scrollHeight; try { const data = await post('/api/sim-qq/message', { text }); pending.remove(); addMessage(data.answer, 'incoming'); } catch (error) { pending.remove(); addMessage(`发送失败：${error.message}`, 'incoming error'); showToast(error.message); } });
(function initDeviceControl() {
  const state = $('deviceState'); const connectButton = $('deviceConnectButton'); const range = $('angleRange'); const angle = $('angleInput');
  if (!state || !connectButton) return;
  const mark = (online, label) => { state.textContent = label; state.className = `device-state ${online ? 'online' : 'offline'}`; setText('deviceConnectionText', online ? '已连接' : '未连接'); connectButton.textContent = online ? '断开设备' : '连接设备'; };
  const report = (payload) => { if (typeof payload.angle === 'number') { range.value = payload.angle; angle.value = payload.angle; setText('deviceAngle', `${payload.angle}°`); } if (payload.type === 'error') showToast(payload.message || '设备命令失败'); };
  const send = (cmd, value) => { if (!deviceSocket || deviceSocket.readyState !== WebSocket.OPEN) { showToast('设备未连接'); return; } const payload = { device_id: DEVICE_ID, cmd }; if (cmd === 'angle') payload.value = Math.max(0, Math.min(180, Number(value))); deviceSocket.send(JSON.stringify(payload)); };
  const connect = () => { if (deviceSocket && [WebSocket.OPEN, WebSocket.CONNECTING].includes(deviceSocket.readyState)) { deviceManualClose = true; deviceSocket.close(); return; } deviceManualClose = false; mark(false, '连接中'); deviceSocket = new WebSocket(DEVICE_WS_URL); deviceSocket.onopen = () => { deviceReconnectDelay = 1000; deviceSocket.send(JSON.stringify({ type: 'auth', device_id: DEVICE_ID, token: DEVICE_TOKEN })); mark(true, '在线'); }; deviceSocket.onmessage = (event) => { try { report(JSON.parse(event.data)); } catch (_) {} }; deviceSocket.onerror = () => mark(false, '连接失败'); deviceSocket.onclose = () => { mark(false, '离线'); if (!deviceManualClose && !deviceReconnectTimer) deviceReconnectTimer = setTimeout(() => { deviceReconnectTimer = null; connect(); deviceReconnectDelay = Math.min(deviceReconnectDelay * 2, 10000); }, deviceReconnectDelay); }; };
  connectButton.addEventListener('click', connect); range.addEventListener('input', () => { angle.value = range.value; }); angle.addEventListener('input', () => { const value = Math.max(0, Math.min(180, Number(angle.value || 0))); range.value = value; }); $('angleButton')?.addEventListener('click', () => send('angle', angle.value)); document.querySelectorAll('[data-device-command]').forEach((button) => button.addEventListener('click', () => send(button.dataset.deviceCommand))); window.addEventListener('beforeunload', () => { if (deviceReconnectTimer) clearTimeout(deviceReconnectTimer); deviceSocket?.close(); });
})();
(async () => { try { const res = await fetch('/api/sim-qq/session'); if (res.ok) setIdentity((await res.json()).identity); } catch (_) {} })();
